"""initial

Revision ID: 18877208e2ba
Revises: 
Create Date: 2025-07-21 14:00:34.781344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18877208e2ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
