"""Add HUMAN_ASSISTANCE to Intent enum

Revision ID: 61c5ab9f4888
Revises: 7377f92f22bf
Create Date: 2025-08-07 15:31:56.560945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61c5ab9f4888'
down_revision = '7377f92f22bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE intent ADD VALUE IF NOT EXISTS 'HUMAN_ASSISTANCE'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE intent DROP VALUE IF EXISTS 'HUMAN_ASSISTANCE'")
    # ### end Alembic commands ###
