"""Add new intent enum values for products

Revision ID: 7377f92f22bf
Revises: 826f19823fa5
Create Date: 2025-08-04 13:16:46.367155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7377f92f22bf'
down_revision = '826f19823fa5'
branch_labels = None
depends_on = None


def upgrade():
    # Set statement timeout to 1 hour (3600000ms) to prevent hanging
    op.execute(sa.text("SET statement_timeout = 3600000;"))
    
    # Start transaction
    connection = op.get_bind()
    
    try:
        # First, add new enum values
        print("Adding new enum values...")
        op.execute(sa.text("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'PRODUCT_LIST' AND enumtypid = 'intent'::regtype) THEN
                ALTER TYPE intent ADD VALUE 'PRODUCT_LIST';
            END IF;
            
            IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'PRODUCT_CATEGORIES' AND enumtypid = 'intent'::regtype) THEN
                ALTER TYPE intent ADD VALUE 'PRODUCT_CATEGORIES';
            END IF;
            
            IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'PRODUCT_DETAILS' AND enumtypid = 'intent'::regtype) THEN
                ALTER TYPE intent ADD VALUE 'PRODUCT_DETAILS';
            END IF;
            
            IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'PRODUCT_LIST_BY_CATEGORY' AND enumtypid = 'intent'::regtype) THEN
                ALTER TYPE intent ADD VALUE 'PRODUCT_LIST_BY_CATEGORY';
            END IF;
        END
        $$;
        """))
        
        print("Migration completed successfully!")
        
    except Exception as e:
        print(f"Error during migration: {str(e)}")
        connection.execute(sa.text("ROLLBACK"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    ALTER TYPE intent RENAME TO intent_new;
    """)
    
    # Revert to the original enum values
    op.execute("""
    CREATE TYPE intent AS ENUM 
    ('PRODUCT_INQUIRY', 'GENERAL_QUESTION', 'GREETING', 'STORE_INFO', 
     'STORE_HOURS', 'STORE_CONTACT', 'STORE_PROMOTIONS', 
     'STORE_PAYMENT_METHODS', 'STORE_SOCIAL_MEDIA', 'STORE_LOCATION', 'OTHER', 'PRODUCT_LIST', 'PRODUCT_CATEGORIES', 'PRODUCT_DETAILS', 'PRODUCT_LIST_BY_CATEGORY');
    """)
    
    # Convert messages.intent to text
    op.execute("""
    ALTER TABLE messages 
    ALTER COLUMN intent TYPE TEXT USING intent::TEXT;
    """)
    
    # Convert chats.initial_intent if it exists
    op.execute("""
    DO $$
    BEGIN
        IF EXISTS (SELECT 1 FROM information_schema.columns 
                  WHERE table_name = 'chats' AND column_name = 'initial_intent') THEN
            EXECUTE 'ALTER TABLE chats ALTER COLUMN initial_intent TYPE TEXT USING initial_intent::TEXT';
        END IF;
    END $$;
    """)
    
    # Update messages table with new enum values
    op.execute("""
    UPDATE messages 
    SET intent = CASE 
        WHEN intent IN ('STORE_INFO', 'STORE_HOURS', 'STORE_CONTACT', 'STORE_PROMOTIONS', 
                      'STORE_PAYMENT_METHODS', 'STORE_SOCIAL_MEDIA', 'STORE_LOCATION') 
        THEN 'OTHER'
        ELSE UPPER(intent)
    END;
    """)
    
    # Update chats table if it has the column
    op.execute("""
    DO $$
    BEGIN
        IF EXISTS (SELECT 1 FROM information_schema.columns 
                  WHERE table_name = 'chats' AND column_name = 'initial_intent') THEN
            EXECUTE 'UPDATE chats SET initial_intent = CASE ' ||
                    'WHEN initial_intent IN (''STORE_INFO'', ''STORE_HOURS'', ''STORE_CONTACT'', ''STORE_PROMOTIONS'', ' ||
                    '''STORE_PAYMENT_METHODS'', ''STORE_SOCIAL_MEDIA'', ''STORE_LOCATION'') ' ||
                    'THEN ''OTHER'' ' ||
                    'ELSE UPPER(initial_intent) END';
        END IF;
    END $$;
    """)
    
    # Convert messages.intent back to old enum type
    op.execute("""
    ALTER TABLE messages 
    ALTER COLUMN intent TYPE intent USING intent::intent;
    """)
    
    # Convert chats.initial_intent if it exists
    op.execute("""
    DO $$
    BEGIN
        IF EXISTS (SELECT 1 FROM information_schema.columns 
                  WHERE table_name = 'chats' AND column_name = 'initial_intent') THEN
            EXECUTE 'ALTER TABLE chats ALTER COLUMN initial_intent TYPE intent USING initial_intent::intent';
        END IF;
    END $$;
    """)
    
    # Remove the new enum
    op.execute("""
    DROP TYPE intent_new;
    """)
    # ### end Alembic commands ###
