"""Add new intent enum values

Revision ID: 826f19823fa5
Revises: c60ccca04dfa
Create Date: 2025-08-04 11:25:44.028410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826f19823fa5'
down_revision = 'c60ccca04dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    ALTER TYPE intent RENAME TO intent_old;
    """)
    
    # Create new enum type with all values in uppercase
    op.execute("""
    CREATE TYPE intent AS ENUM 
    ('PRODUCT_INQUIRY', 'GENERAL_QUESTION', 'GREETING', 'STORE_INFO', 
     'STORE_HOURS', 'STORE_CONTACT', 'STORE_PROMOTIONS', 
     'STORE_PAYMENT_METHODS', 'STORE_SOCIAL_MEDIA', 'STORE_LOCATION', 'OTHER');
    """)
    
    # First, convert messages.intent to text
    op.execute("""
    ALTER TABLE messages 
    ALTER COLUMN intent TYPE TEXT USING intent::TEXT;
    """)
    
    # Then handle chats.initial_intent if it exists
    op.execute("""
    DO $$
    BEGIN
        IF EXISTS (SELECT 1 FROM information_schema.columns 
                  WHERE table_name = 'chats' AND column_name = 'initial_intent') THEN
            EXECUTE 'ALTER TABLE chats ALTER COLUMN initial_intent TYPE TEXT USING initial_intent::TEXT';
        END IF;
    END $$;
    """)
    
    # Update messages table to uppercase
    op.execute("""
    UPDATE messages 
    SET intent = UPPER(intent);
    """)
    
    # Update chats table if it has the column
    op.execute("""
    DO $$
    BEGIN
        IF EXISTS (SELECT 1 FROM information_schema.columns 
                  WHERE table_name = 'chats' AND column_name = 'initial_intent') THEN
            EXECUTE 'UPDATE chats SET initial_intent = UPPER(initial_intent)';
        END IF;
    END $$;
    """)
    
    # Convert messages.intent to new enum type
    op.execute("""
    ALTER TABLE messages 
    ALTER COLUMN intent TYPE intent USING intent::intent;
    """)
    
    # Convert chats.initial_intent if it exists
    op.execute("""
    DO $$
    BEGIN
        IF EXISTS (SELECT 1 FROM information_schema.columns 
                  WHERE table_name = 'chats' AND column_name = 'initial_intent') THEN
            EXECUTE 'ALTER TABLE chats ALTER COLUMN initial_intent TYPE intent USING initial_intent::intent';
        END IF;
    END $$;
    """)
    
    # Remove the old enum
    op.execute("""
    DROP TYPE intent_old;
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    ALTER TYPE intent RENAME TO intent_new;
    """)
    
    # Revert to the original enum values
    op.execute("""
    CREATE TYPE intent AS ENUM 
    ('PRODUCT_INQUIRY', 'GENERAL_QUESTION', 'GREETING', 'OTHER');
    """)
    
    # Convert messages.intent to text
    op.execute("""
    ALTER TABLE messages 
    ALTER COLUMN intent TYPE TEXT USING intent::TEXT;
    """)
    
    # Convert chats.initial_intent if it exists
    op.execute("""
    DO $$
    BEGIN
        IF EXISTS (SELECT 1 FROM information_schema.columns 
                  WHERE table_name = 'chats' AND column_name = 'initial_intent') THEN
            EXECUTE 'ALTER TABLE chats ALTER COLUMN initial_intent TYPE TEXT USING initial_intent::TEXT';
        END IF;
    END $$;
    """)
    
    # Update messages table with new enum values
    op.execute("""
    UPDATE messages 
    SET intent = CASE 
        WHEN intent IN ('STORE_INFO', 'STORE_HOURS', 'STORE_CONTACT', 'STORE_PROMOTIONS', 
                      'STORE_PAYMENT_METHODS', 'STORE_SOCIAL_MEDIA', 'STORE_LOCATION') 
        THEN 'OTHER'
        ELSE UPPER(intent)
    END;
    """)
    
    # Update chats table if it has the column
    op.execute("""
    DO $$
    BEGIN
        IF EXISTS (SELECT 1 FROM information_schema.columns 
                  WHERE table_name = 'chats' AND column_name = 'initial_intent') THEN
            EXECUTE 'UPDATE chats SET initial_intent = CASE ' ||
                    'WHEN initial_intent IN (''STORE_INFO'', ''STORE_HOURS'', ''STORE_CONTACT'', ''STORE_PROMOTIONS'', ' ||
                    '''STORE_PAYMENT_METHODS'', ''STORE_SOCIAL_MEDIA'', ''STORE_LOCATION'') ' ||
                    'THEN ''OTHER'' ' ||
                    'ELSE UPPER(initial_intent) END';
        END IF;
    END $$;
    """)
    
    # Convert messages.intent back to old enum type
    op.execute("""
    ALTER TABLE messages 
    ALTER COLUMN intent TYPE intent USING intent::intent;
    """)
    
    # Convert chats.initial_intent if it exists
    op.execute("""
    DO $$
    BEGIN
        IF EXISTS (SELECT 1 FROM information_schema.columns 
                  WHERE table_name = 'chats' AND column_name = 'initial_intent') THEN
            EXECUTE 'ALTER TABLE chats ALTER COLUMN initial_intent TYPE intent USING initial_intent::intent';
        END IF;
    END $$;
    """)
    
    # Remove the new enum
    op.execute("""
    DROP TYPE intent_new;
    """)
    # ### end Alembic commands ###
