"""Add transfer_inquiry_id and transfer_query to chats table

Revision ID: 93a829c5172d
Revises: 61c5ab9f4888
Create Date: 2025-08-08 17:02:38.112673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a829c5172d'
down_revision = '61c5ab9f4888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('transfer_inquiry_id', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('transfer_query', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'transfer_query')
    op.drop_column('chats', 'transfer_inquiry_id')
    # ### end Alembic commands ###
